### ISSUE TITLE
Not running on google colab

### ISSUE THREAD

**Issue by JanAlie** [virufy/virufy-covid#2]
![ISSUE](https://user-images.githubusercontent.com/38201594/121371704-30067780-c957-11eb-907e-5542242ba4b5.PNG)
Hey folks , I hope you're doing well. While just simply running this cough_model notebook file in google colab. It shows the error , the snapshot of error is attached with it .
kindly help me in solving the issue.
Thanks in advance.

**Comment by KAIMAN0** [comment]
try change **super(Callback,self).__init__()** to **super().__init__()**

**Comment by amilkh** [comment]
Hi all! We are working to update the GitHub codebase with working code, please do give us a few weeks for this, and in meantime please try to workaround these and study / learn from our codes / data put up here.

**Comment by JanAlie** [comment]
Ok sounds good.
But can you please send me the accurate cough_model notebook file so that i
can submit to it to my office because we are also interested in doing
that to our problem status.
Thanksgiving.

**Comment by amilkh** [comment]
If you'd like to collaborate on company basis, please feel free to email us the contact link on our website!

**Comment by JanAlie** [comment]
It'll be done in futuristic approaches, but currently i  need that
individually and can't wait for this to be resolved.
Because the reason why I'm insisting is the case of deadlines.
I hope you understand my cause .
Thanksgiving
