### ISSUE TITLE
'cough_model.ipynb' - Not working on  google colab

### ISSUE THREAD

**Issue by arunsignaltech** [virufy/virufy-covid#4]
As suggested , I  did this change : 'super(Callback,self).init()' to 'super().init()'
I am getting this errors , looks like issue with custom data generator that samples the data  for the ensemble model .
Please see the more information in the attached image 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-38e7cfe83325> in <module>()
    139                   validation_data=VAL,
    140                   verbose=2,
--> 141                   callbacks=[evaluator, checkpointer])
    
4 frames
/usr/local/lib/python3.7/dist-packages/keras/engine/data_adapter.py in select_data_adapter(x, y)
    976         "Failed to find data adapter that can handle "
    977         "input: {}, {}".format(
--> 978             _type_name(x), _type_name(y)))
    979   elif len(adapter_cls) > 1:
    980     raise RuntimeError(

ValueError: Failed to find data adapter that can handle input: <class '__main__.TripleInputGenerator'>, <class 'NoneType'>

![image](https://user-images.githubusercontent.com/87971877/126962439-4f115516-3212-4e4e-81a6-b0bdb34cb6fa.png)
![image](https://user-images.githubusercontent.com/87971877/126962551-a320b0cb-9c3b-495e-90dd-06712664747d.png)

**Comment by amilkh** [comment]
Hi all! We are working to update the GitHub codebase with working code, please do give us a few weeks for this, and in meantime please try to workaround these and study / learn from our codes / data put up here.
